# Numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
print(arr.ndim)

1


In [18]:
arr1=np.array([[1,2,3,4],[4,3,5,3]])
print(arr1)
print(arr1.ndim)

[[1 2 3 4]
 [4 3 5 3]]
2


In [19]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr4 = np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
arr5 = np.identity((4))
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
arr7 = np.linspace(10,20,4)
arr7

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [30]:
arr8 = np.arange(10,20,2)
arr8

array([10, 12, 14, 16, 18])

In [34]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
arr8

array([10, 12, 14, 16, 18])

In [36]:
arr8=arr4.copy()
arr8

array([[1., 1., 1.],
       [1., 1., 1.]])

In [37]:
arr8.shape

(2, 3)

In [39]:
arr9 = np.array([[[1,3],[3,4]],[[5,6],[4,6]]])
print(arr9.ndim)
print(arr9)

3
[[[1 3]
  [3 4]]

 [[5 6]
  [4 6]]]


In [47]:
arr10 = np.array([[[[1,2]]]])
print(arr10)
print(arr10.ndim)
print(arr10.shape)

[[[[1 2]]]]
4
(1, 1, 1, 2)


In [46]:
arr10.size

2

In [48]:
arr10.itemsize

4

In [51]:
print(arr10)
print(arr10.dtype)

[[[[1 2]]]]
int32


In [55]:
arr4.astype('float')


array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
lista=range(100)
arr11 = np.arange(100)


In [60]:
import sys
print(sys.getsizeof(12)*len(lista))

2800


In [61]:
print(arr11.itemsize*arr11.size)

400


# Indexing ,Slicing and Iteration


In [68]:
arr = np.arange(24).reshape(6,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [110]:
# arr[(rows),(coloumns)]
arr[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [112]:
arr[4:6,0:2]

array([[16, 17],
       [20, 21]])

In [113]:
arr[2:6,1:3]

array([[ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [14]:
# import numpy as np
arr2 = np.arange(30).reshape(5,6)
print(arr2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [9]:
print(arr2[2:4])

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [16]:
print(arr2[2:4,1:5])

[[13 14 15 16]
 [19 20 21 22]]


In [26]:
print(arr2[::2,1::2])

[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [35]:
# for iterator in iterable 
for i in arr2:
    print(i)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


In [36]:
# apply filter on every pixel of image
for i in np.nditer(arr2):
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


# Numpy Operation


In [37]:
new_arr1 = np.array([1,2,3,4,5,6])
new_arr2 = np.array([4,5,6,7,8,9])
print(new_arr1)
print(new_arr2)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [39]:
# Addition 
print(new_arr1+new_arr2)
# substraction
print(new_arr1-new_arr2)

[ 5  7  9 11 13 15]
[-3 -3 -3 -3 -3 -3]


In [40]:
# Multiplication
print(new_arr1*new_arr2)

[ 4 10 18 28 40 54]


In [44]:
# Multiply by 2
print(new_arr1*2)

[ 2  4  6  8 10 12]


In [43]:
# power
print(new_arr1**2)

[ 1  4  9 16 25 36]


In [45]:
new_arr1>3

array([False, False, False,  True,  True,  True])

In [47]:
new_arr3 = np.arange(6).reshape(2,3)
new_arr4 = np.arange(6).reshape(3,2)
print(new_arr3)
print(new_arr4)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [50]:
new_arr3.dot(new_arr4)

array([[10, 13],
       [28, 40]])

In [48]:
new_arr5 = new_arr3.dot(new_arr4)
print(new_arr5)

[[10 13]
 [28 40]]


In [57]:
new_arr5.max()

40

In [58]:
new_arr5.min()

10

In [59]:
new_arr5.min(axis=0)

array([10, 13])

In [60]:
new_arr5.max(axis=0)

array([28, 40])

In [61]:
new_arr5.min(axis=1)

array([10, 28])

In [63]:
new_arr5.max(axis=1)

array([13, 40])

In [64]:
new_arr5.mean()

22.75

In [65]:
new_arr5.std()

12.07010770457331

In [72]:
# Reshaping Numpy Arrays
print(new_arr5)
print(new_arr5.ndim)


[[10 13]
 [28 40]]
2


In [75]:
# convert higher dimensional to one dimension
new_arr6=new_arr5.ravel()
print(new_arr6)
print(new_arr6.ndim)

[10 13 28 40]
1


In [77]:
print(new_arr5)
new_arr5.transpose()

[[10 13]
 [28 40]]


array([[10, 28],
       [13, 40]])

In [91]:
new_arr6 = np.arange(4).reshape(2,2)
new_arr6

array([[0, 1],
       [2, 3]])

In [92]:
np.hstack((new_arr5,new_arr6))

array([[10, 13,  0,  1],
       [28, 40,  2,  3]])

In [93]:
np.vstack((new_arr5,new_arr6))

array([[10, 13],
       [28, 40],
       [ 0,  1],
       [ 2,  3]])

In [95]:
np.hsplit(new_arr5,2)

[array([[10],
        [28]]),
 array([[13],
        [40]])]

In [96]:
np.vsplit(new_arr5,2)

[array([[10, 13]]), array([[28, 40]])]