In [2]:
import pandas as pd
import numpy as np

In [4]:
data = np.arange(0,20).reshape(5,4)
print(data)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [8]:
df=pd.DataFrame(data,index=['Row1','Row2','Row3','Row4','Row5'],columns=['Column1','Column2','Column3','Column4'])
print(df)

      Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19


In [11]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [12]:
df.tail()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [19]:
df.sample(3)

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row4       12       13       14       15
Row3        8        9       10       11

In [20]:
df.columns

Index(['Column1', 'Column2', 'Column3', 'Column4'], dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int32
 1   Column2  5 non-null      int32
 2   Column3  5 non-null      int32
 3   Column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [22]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [23]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [25]:
print(type(df['Column1']))

<class 'pandas.core.series.Series'>


In [31]:
##Indexing
## columnname,rowindex[loc],rowindex columnindex number[.iloc]
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int32

In [32]:
df[['Column1','Column4','Column3']]

Column1  Column4  Column3
Row1        0        3        2
Row2        4        7        6
Row3        8       11       10
Row4       12       15       14
Row5       16       19       18

In [35]:
# Row index  loc
df.loc[['Row3','Row4']]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [37]:
df.loc[['Row1']]

Column1  Column2  Column3  Column4
Row1        0        1        2        3

In [38]:
df.loc['Row1']

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int32

In [53]:
# Row,colums using iloc method
df.iloc[1:6,1:3]

Column2  Column3
Row2        5        6
Row3        9       10
Row4       13       14
Row5       17       18

In [54]:
df.iloc[:,:]

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [58]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [59]:
##convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [3]:
df1=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1",
                                                      "Row2"],columns=["Column1",
                                                                             "Column2",
                                                                             "Column3",
                                                                             ])
print(df1)

      Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4


In [4]:
df1.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [12]:
df1.Column3.unique()

array([2, 4], dtype=int64)

In [19]:
df1['Column3'].value_counts()

4    1
2    1
Name: Column3, dtype: int64

In [20]:
df1['Column3']>2

Row1    False
Row2     True
Name: Column3, dtype: bool

In [21]:
df1

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4